version: "1"
services:
    # Database Service
    db:
        image: postgres:17.6
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432

        environment:
            - POSTGRES_DB=postDB
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456

    # Manage Database Service
    adminer:
        image: adminer:standalone
        restart: always
        ports:
            - 8080:8080
